python fit_neural_data.py --whichopt 1 --weight_decay 1e-3 --expId inst_cate_res18_obj --gpu 0 \
    --loadexpId res18_inst_cate_1 \
    --cacheDirName neural_fitting_inst \
    --it_nodes encode_[2:1:10],category_2 \
    --v4_nodes encode_[2:1:10],category_2 \
    --loadport 27009 --tpu_flag 1 --fre_valid 160 --fre_metric 160 \
    --use_dataset_inter --objectome_zip --gen_features 1 \
    --image_prefix /home/chengxuz/objectome --batchsize 60 \
    --gen_hdf5path ~/resnet18_inst_cate_on_objectome.hdf5 \
    --network_func get_resnet_18_inst_and_cate \
    --loaddbname combine_instance
